In [1]:
import numpy as np

In [2]:
array = np.array([12,21,35,36,39])
print(array)

[12 21 35 36 39]


In [3]:
array_new = np.array([23,45,56,87,21,13,24,34,64,99])
print(array_new.shape)

(10,)


In [6]:
x = array_new.reshape(2,5)
print(x)

[[23 45 56 87 21]
 [13 24 34 64 99]]


In [7]:
print("Matrix Shape: ",x.shape)

Matrix Shape:  (2, 5)


In [8]:
print("Dimension of the Matrix: ",x.ndim)

Dimension of the Matrix:  2


In [9]:
print("Size of the Matrix: ",x.size)

Size of the Matrix:  10


In [10]:
print("Type of the Matrix: ",type(x))

Type of the Matrix:  <class 'numpy.ndarray'>


In [16]:
array3 = np.array([[2,4,6,8,10],[10,12,14,16,18]])

In [17]:
print(array3)

[[ 2  4  6  8 10]
 [10 12 14 16 18]]


In [18]:
array3.shape

(2, 5)

In [19]:
zeros = np.zeros((2,2))

In [20]:
print(zeros)

[[0. 0.]
 [0. 0.]]


In [21]:
ones = np.ones((1,2))
print(ones)

[[1. 1.]]


In [23]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.20160575e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [24]:
np.arange(1,21,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [25]:
np.linspace(2.0,3.0,5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [26]:
a = np.array([2,4,6])
b = np.array([1,3,5])
c = np.array([7,8,9])
print(a+b+c)
print(a-b+c)
print(b**3)

[10 15 20]
[ 8  9 10]
[  1  27 125]


In [29]:
list = [2,4,6,8,10]
array = np.array([1,3,5,7,9])
print(list)
print(array)

[2, 4, 6, 8, 10]
[1 3 5 7 9]


In [30]:
x = np.array([2,4,6,8,10])

In [31]:
a = x
b = x

In [34]:
b[-1] = 9
print(x,a,b)

[2 4 6 8 9] [2 4 6 8 9] [2 4 6 8 9]


In [35]:
a[0] = 1

In [36]:
d = a.copy()
print(d)

[1 4 6 8 9]


In [37]:
d

array([1, 4, 6, 8, 9])

In [38]:
x[0:3]

array([1, 4, 6])

In [41]:
x[::-1]

array([9, 8, 6, 4, 1])

In [42]:
k = np.array([[2,4,6,8,10],[1,3,5,7,9]])
k

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [45]:
print(k[0,0])

2


In [46]:
print(k[:,2])

[6 5]


In [47]:
k[1,:3]

array([1, 3, 5])

In [48]:
k[1,1:3]

array([3, 5])

In [49]:
k[-1,:]

array([1, 3, 5, 7, 9])

In [50]:
k[-1,:3]

array([1, 3, 5])

In [51]:
k[:,-1]

array([10,  9])

In [52]:
k = k.ravel()

In [53]:
print(k)

[ 2  4  6  8 10  1  3  5  7  9]


In [54]:
k.T

array([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])